import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";

/** Directory inside each worktree holding the generated session files. */
export const SESSION_DIR = ".sidequest";

export interface AutorunFiles {
  dir: string;
  promptFile: string;
  scriptFile: string;
  pendingFile: string;
}

export function autorunPaths(worktreePath: string): AutorunFiles {
  const dir = join(worktreePath, SESSION_DIR);
  return {
    dir,
    promptFile: join(dir, "prompt.md"),
    scriptFile: join(dir, "autorun.sh"),
    pendingFile: join(dir, "pending"),
  };
}

/** POSIX single-quote escaping: close, escape, reopen. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export interface WriteAutorunOptions {
  worktreePath: string;
  prompt: string;
  agentCommand: string;
  agentArgs: string[];
  /** Human label for comments only, e.g. "Codex". */
  agentLabel?: string;
  /** Starting terminal title; the agent may replace it. */
  title?: string;
}

/**
 * Write the prompt and a run-once launcher script into the worktree.
 *
 * Warp has historically ignored `exec` entries when a launch configuration is
 * opened via the warp:// deeplink (warpdotdev/warp#9007), and the shell hook is
 * opt-in, so both paths may fire — or only one of them. The script claims the
 * `pending` marker with an atomic rename, so whichever path runs first starts
 * the agent and the other exits quietly.
 */
export async function writeAutorun(options: WriteAutorunOptions): Promise<AutorunFiles> {
  const paths = autorunPaths(options.worktreePath);
  await mkdir(paths.dir, { recursive: true });

  await writeFile(paths.promptFile, `${options.prompt}\n`, "utf8");
  await writeFile(paths.pendingFile, "", "utf8");
  await writeFile(paths.scriptFile, renderScript(options), "utf8");
  await chmod(paths.scriptFile, 0o755);

  return paths;
}

function renderScript(options: WriteAutorunOptions): string {
  const command = [options.agentCommand, ...options.agentArgs].map(shellQuote).join(" ");
  const agentLine = options.agentLabel ? `# Agent: ${options.agentLabel}\n` : "";
  const title = shellQuote((options.title ?? "sidequest").replace(/[\u0000-\u001f\u007f]/g, ""));

  return `#!/usr/bin/env bash
# Generated by sidequest. Regenerated for every session; safe to delete.
${agentLine}set -uo pipefail

session_dir="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
worktree="$(dirname "$session_dir")"
pending="$session_dir/pending"
started="$session_dir/started"

# Claim the run. mv is atomic, so exactly one caller gets past this line even if
# Warp's launch config and the shell hook both fire.
if ! mv "$pending" "$started" 2>/dev/null; then
  exit 0
fi

cd "$worktree" || exit 1

if [ ! -f "$session_dir/prompt.md" ]; then
  echo "Sidequest: prompt.md is missing from $session_dir" >&2
  exit 1
fi

printf '\\033]0;%s\\007' ${title}
${command} "$(cat "$session_dir/prompt.md")"
`;
}

/**
 * The snippet users add to their shell rc. It runs the autorun script when a
 * shell starts inside a worktree that still has an unclaimed session.
 *
 * It waits for the first prompt rather than running while the rc file is
 * sourced: Warp finishes setting a session up after the rc files, and an
 * agent started before then takes over the terminal mid-bootstrap.
 */
export function shellHookSource(): string {
  return `# sidequest shell hook
# Starts the agent session when a shell opens in a sidequest worktree.
# Added by: sidequest install-hook
_sidequest_autorun() {
  [ -n "\${SIDEQUEST_AUTORUN_RAN:-}" ] && return 0
  SIDEQUEST_AUTORUN_RAN=1
  [ -f "$PWD/${SESSION_DIR}/pending" ] || return 0
  [ -x "$PWD/${SESSION_DIR}/autorun.sh" ] || return 0
  "$PWD/${SESSION_DIR}/autorun.sh"
}
if [ -n "\${ZSH_VERSION:-}" ]; then
  autoload -Uz add-zsh-hook
  _sidequest_first_prompt() {
    add-zsh-hook -d precmd _sidequest_first_prompt
    _sidequest_autorun
  }
  add-zsh-hook precmd _sidequest_first_prompt
elif [ -n "\${BASH_VERSION:-}" ]; then
  PROMPT_COMMAND="_sidequest_autorun\${PROMPT_COMMAND:+;\$PROMPT_COMMAND}"
else
  _sidequest_autorun
fi
`;
}
