import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";

/** Directory inside each worktree holding the generated session files. */
export const SESSION_DIR = ".ccslack";

export interface AutorunFiles {
  dir: string;
  promptFile: string;
  scriptFile: string;
  pendingFile: string;
}

export function autorunPaths(worktreePath: string): AutorunFiles {
  const dir = join(worktreePath, SESSION_DIR);
  return {
    dir,
    promptFile: join(dir, "prompt.md"),
    scriptFile: join(dir, "autorun.sh"),
    pendingFile: join(dir, "pending"),
  };
}

/** POSIX single-quote escaping: close, escape, reopen. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export interface WriteAutorunOptions {
  worktreePath: string;
  prompt: string;
  claudeCommand: string;
  claudeArgs: string[];
}

/**
 * Write the prompt and a run-once launcher script into the worktree.
 *
 * Warp has historically ignored `exec` entries when a launch configuration is
 * opened via the warp:// deeplink (warpdotdev/warp#9007), and the shell hook is
 * opt-in, so both paths may fire — or only one of them. The script claims the
 * `pending` marker with an atomic rename, so whichever path runs first starts
 * Claude and the other exits quietly.
 */
export async function writeAutorun(options: WriteAutorunOptions): Promise<AutorunFiles> {
  const paths = autorunPaths(options.worktreePath);
  await mkdir(paths.dir, { recursive: true });

  await writeFile(paths.promptFile, `${options.prompt}\n`, "utf8");
  await writeFile(paths.pendingFile, "", "utf8");
  await writeFile(paths.scriptFile, renderScript(options), "utf8");
  await chmod(paths.scriptFile, 0o755);

  return paths;
}

function renderScript(options: WriteAutorunOptions): string {
  const command = [options.claudeCommand, ...options.claudeArgs].map(shellQuote).join(" ");

  return `#!/usr/bin/env bash
# Generated by ccslack. Regenerated for every session; safe to delete.
set -uo pipefail

session_dir="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
worktree="$(dirname "$session_dir")"
pending="$session_dir/pending"
started="$session_dir/started"

# Claim the run. mv is atomic, so exactly one caller gets past this line even if
# Warp's launch config and the shell hook both fire.
if ! mv "$pending" "$started" 2>/dev/null; then
  exit 0
fi

cd "$worktree" || exit 1

if [ ! -f "$session_dir/prompt.md" ]; then
  echo "ccslack: prompt.md is missing from $session_dir" >&2
  exit 1
fi

printf '\\033]0;ccslack\\007'
${command} "$(cat "$session_dir/prompt.md")"
`;
}

/**
 * The snippet users add to their shell rc. It runs the autorun script when a
 * shell starts inside a worktree that still has an unclaimed session.
 */
export function shellHookSource(): string {
  return `# ccslack shell hook
# Starts the Claude Code session when a shell opens in a ccslack worktree.
# Added by: ccslack install-hook
_ccslack_autorun() {
  [ -n "\${CCSLACK_AUTORUN_RAN:-}" ] && return 0
  [ -f "$PWD/${SESSION_DIR}/pending" ] || return 0
  [ -x "$PWD/${SESSION_DIR}/autorun.sh" ] || return 0
  CCSLACK_AUTORUN_RAN=1
  "$PWD/${SESSION_DIR}/autorun.sh"
}
_ccslack_autorun
`;
}
