import { spawn } from "node:child_process";
import { chmod, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { HeadlessInvocation } from "../agents/agents.js";
import { SESSION_DIR, shellQuote } from "../warp/autorun.js";

export interface HeadlessFiles {
  /** The runner script, the headless counterpart of autorun.sh. */
  scriptFile: string;
  /** Everything the agent printed, plus when it started and how it ended. */
  logFile: string;
  /** The agent's final answer; only there once it finished cleanly. */
  resultFile: string;
}

/**
 * `result.md` is where another part of Sidequest looks for the answer to post
 * back to Slack, so the name is a contract, not a detail.
 */
export function headlessPaths(worktreePath: string): HeadlessFiles {
  const dir = join(worktreePath, SESSION_DIR);
  return {
    scriptFile: join(dir, "headless.sh"),
    logFile: join(dir, "agent.log"),
    resultFile: join(dir, "result.md"),
  };
}

export interface WriteHeadlessOptions {
  worktreePath: string;
  agentCommand: string;
  /** The user's own agent args; they go after the headless flags. */
  agentArgs: string[];
  headless: HeadlessInvocation;
  agentLabel?: string;
}

/**
 * Write the runner that starts the agent with no terminal. It expects
 * writeAutorun to have put the prompt and pending marker in place, and claims
 * the marker the same way autorun.sh does, so a session only ever runs once.
 */
export async function writeHeadlessRunner(options: WriteHeadlessOptions): Promise<HeadlessFiles> {
  const paths = headlessPaths(options.worktreePath);
  await writeFile(paths.scriptFile, renderHeadlessScript(options), "utf8");
  await chmod(paths.scriptFile, 0o755);
  return paths;
}

export function renderHeadlessScript(options: WriteHeadlessOptions): string {
  const { headless } = options;
  const command = [options.agentCommand, ...headless.args, ...options.agentArgs].map(shellQuote).join(" ");
  const agentLine = options.agentLabel ? `# Agent: ${options.agentLabel}\n` : "";

  // stdin is /dev/null: nobody is there to answer a question, and an agent
  // that waits for one would hang forever instead of failing.
  const runLine =
    headless.result === "stdout"
      ? `${command} "$prompt" </dev/null 2>>"$log" | tee "$partial" >>"$log"
status=\${PIPESTATUS[0]}
if [ "$status" -eq 0 ]; then mv "$partial" "$result"; else rm -f "$partial"; fi`
      : `${command} "$prompt" </dev/null >>"$log" 2>&1
status=$?`;

  return `#!/usr/bin/env bash
# Generated by sidequest. Runs the agent with no terminal; safe to delete.
${agentLine}set -uo pipefail

session_dir="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
worktree="$(dirname "$session_dir")"
pending="$session_dir/pending"
started="$session_dir/started"
log="$session_dir/agent.log"
result="$session_dir/result.md"
partial="$session_dir/result.md.partial"

# Claim the run, exactly as autorun.sh does, so it never starts twice.
if ! mv "$pending" "$started" 2>/dev/null; then
  exit 0
fi

cd "$worktree" || exit 1

if [ ! -f "$session_dir/prompt.md" ]; then
  echo "Sidequest: prompt.md is missing from $session_dir" >>"$log"
  exit 1
fi

rm -f "$result" "$partial"
prompt="$(cat "$session_dir/prompt.md")"
echo "sidequest: started $(date -u +%Y-%m-%dT%H:%M:%SZ)" >>"$log"
${runLine}
echo "sidequest: finished $(date -u +%Y-%m-%dT%H:%M:%SZ), exit $status" >>"$log"
exit "$status"
`;
}

/**
 * Start the runner detached from the daemon, so restarting or stopping
 * Sidequest doesn't take a half-finished session down with it. Resolves once
 * the process exists; the run itself is reported in its log.
 */
export function spawnHeadless(scriptFile: string, cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(scriptFile, [], { cwd, detached: true, stdio: "ignore" });
    child.once("error", reject);
    child.once("spawn", () => {
      child.unref();
      resolve();
    });
  });
}
